version: "3.8"

services:
  shkeeper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shkeeper-dev
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/shkeeper.io/instance
      - ./shkeeper:/shkeeper.io/shkeeper:ro
    environment:
      - METRICS_USERNAME=admin
      - METRICS_PASSWORD=admin
      - FORCE_WALLET_ENCRYPTION=false
      - UNCONFIRMED_TX_NOTIFICATION=false
      - DEV_MODE=true
    restart: unless-stopped

volumes:
  shkeeper_data:
    driver: local
